/* Sample IxDF status lines for the public Vercel demo (no real transfers). */
window.VX_SAMPLES = {
  stage: [
    "INITIALIZATION | effective configuration — four folders",
    "  CONFIG | source=demo replay",
    "  CONFIG | path=./config.yaml",
    "  CONFIG | backend=local",
    "  CONFIG | folders (upload: source_dir→staging_dir; retrieve: results_dir→retrieve_to)",
    "  CONFIG | source_dir=/demo/run-42/source  (1 local upload source)",
    "  CONFIG | staging_dir=/demo/run-42/staging  (2 linux upload destination)",
    "  CONFIG | results_dir=/demo/run-42/results  (3 linux logs/results (separate from upload))",
    "  CONFIG | retrieve_to=/demo/run-42/retrieved  (4 local retrieve destination)",
    "INITIALIZATION | 2 file(s) to upload  local_source=/demo/run-42/source  linux_upload=/demo/run-42/staging",
    "FILE       | meta.txt  size=8  checksum=1afd1b403a9a…",
    "FILE       | payload.txt  size=15  checksum=14274f8239b5…",
    "TRANSFER   | → /demo/run-42/staging/meta.txt",
    "VERIFY     | OK   size=8 checksum=1afd1b403a9a…",
    "SUCCESS    | meta.txt copied and checked at /demo/run-42/staging/meta.txt",
    "TRANSFER   | → /demo/run-42/staging/payload.txt",
    "VERIFY     | OK   size=15 checksum=14274f8239b5…",
    "SUCCESS    | payload.txt copied and checked at /demo/run-42/staging/payload.txt",
    "SUMMARY    | OK  2/2 files staged",
    "NEXT       | All 2 file(s) staged. Safe to continue.",
  ],
  "stage-dry": [
    "INITIALIZATION | effective configuration — four folders",
    "  CONFIG | source=demo replay",
    "  CONFIG | path=./config.yaml",
    "  CONFIG | backend=local",
    "  CONFIG | source_dir=/demo/run-42/source  (1 local upload source)",
    "  CONFIG | staging_dir=/demo/run-42/staging  (2 linux upload destination)",
    "  CONFIG | results_dir=/demo/run-42/results  (3 linux logs/results (separate from upload))",
    "  CONFIG | retrieve_to=/demo/run-42/retrieved  (4 local retrieve destination)",
    "INITIALIZATION | 2 file(s) to upload  local_source=/demo/run-42/source  linux_upload=/demo/run-42/staging",
    "FILE       | meta.txt  size=8  checksum=1afd1b403a9a…",
    "FILE       | payload.txt  size=15  checksum=14274f8239b5…",
    "DRY-RUN    | no files will be written",
    "TRANSFER   | would → /demo/run-42/staging/meta.txt",
    "TRANSFER   | would → /demo/run-42/staging/payload.txt",
    "SUMMARY    | OK  2/2 files would be staged (dry-run)",
    "NEXT       | All 2 file(s) would be staged (dry-run). Safe to continue.",
  ],
  retrieve: [
    "INITIALIZATION | effective configuration — four folders",
    "  CONFIG | source=demo replay",
    "  CONFIG | path=./config.yaml",
    "  CONFIG | backend=local",
    "  CONFIG | source_dir=/demo/run-42/source  (1 local upload source)",
    "  CONFIG | staging_dir=/demo/run-42/staging  (2 linux upload destination)",
    "  CONFIG | results_dir=/demo/run-42/results  (3 linux logs/results (separate from upload))",
    "  CONFIG | retrieve_to=/demo/run-42/retrieved  (4 local retrieve destination)",
    "INITIALIZATION | listing linux logs/results folder  linux_logs=/demo/run-42/results",
    "INITIALIZATION | 2 file(s) to retrieve  linux_logs=/demo/run-42/results  local_retrieve=/demo/run-42/retrieved",
    "TRANSFER   | ← /demo/run-42/results/answer.txt",
    "VERIFY     | OK   size=3 checksum=084c799cd551…",
    "SUCCESS    | answer.txt saved to /demo/run-42/retrieved/answer.txt",
    "TRANSFER   | ← /demo/run-42/results/test.log",
    "VERIFY     | OK   size=5 checksum=c26de83abdc9…",
    "SUCCESS    | test.log saved to /demo/run-42/retrieved/test.log",
    "SUMMARY    | OK  2/2 files retrieved",
    "NEXT       | All 2 file(s) retrieved. Safe to continue.",
  ],
};
